name: Testes Mobile com Emulador

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-mobile:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar testes
        run: mvn test

