name: Testes Mobile com Emulador

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-mobile:
    runs-on: self-hosted

    steps:
      - name: 🔄 Checkout do código
        uses: actions/checkout@v3

      - name: ☕ Verificar Java
        run: java -version

      - name: 📱 Iniciar emulador Android
        run: |
          $ANDROID_HOME/emulator/emulator -avd emulator-5554 -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82

      - name: 🚀 Iniciar Appium
        run: appium &

      - name: 🧪 Executar testes
        run: mvn test

